### ISSUE TITLE
[Bug]: Elytra invisible withe white lightning cape

### ISSUE THREAD

**Issue by Erdbeerbaumhonig** [NoRiskClient/issues#525] opened 2024-11-08 10:09 UTC
### How to reproduce ?

I recently bought a anmietet Cape, workd fine. Then i loaded my singleplayer world and saw my Elytra is invisible. I've tried troubleshooting by removing all addons and mods, but the issue persists. If you need any further information, my Discord is "Erdbeerbaumhonig". Attached are screenshots showing this.

![Screenshot 2024-11-08 105814](https://github.com/user-attachments/assets/5eafc657-7870-435b-8a86-14222f780d96)
![Screenshot 2024-11-08 105824](https://github.com/user-attachments/assets/639d1a71-8b43-444e-a80e-2a4f259b309e)
![Screenshot 2024-11-08 105832](https://github.com/user-attachments/assets/0b03b2f3-4b60-4b14-a165-ca7b64822e03)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by MeisterAH** [comment] 2024-11-08 15:57
duplicate of https://github.com/NoRiskClient/issues/issues/507

**Closed by MeisterAH** 2024-11-08 15:57 UTC
Labels: bug, needs validation
