### ISSUE TITLE
[Bug]: Modules draw a freezed copy

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#275] opened 2024-07-20 10:43 UTC
### What happened?

![2024-07-20_12 36 22_mcreal_primary](https://github.com/user-attachments/assets/33f333b5-de53-4824-a298-e4f3abd76e19)
(I moved the original to see the copy)

It seems to happen randomly.
The original still works, but you can see the copy behind it.
The related log lines are in Relevant log output.

### How to reproduce ?

As I don't know what caused this issue, I don't know how to reproduce it.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug, Windows

### Branch (for client bugs)

1.21

### Relevant log output

```shell
[12:04:31] [Render thread/INFO]: Saving Profile Default...
[12:04:31] [Render thread/INFO]: Saving Profile Default...
[12:04:31] [Render thread/INFO]: Saving Profile Default...
[12:04:31] [Render thread/INFO]: Adding NoRiskClient Ui to Hud...
[12:04:31] [Render thread/INFO]: Adding NoRiskClient Ui to Hud...
[12:04:31] [Render thread/INFO]: Adding NoRiskClient Ui to Hud...
```

**Comment by BigBrainRobin29** [comment] 2024-07-20 10:47
Same as #263

**Comment by SleepyPxnda** [comment] 2024-07-20 19:59
Duplicate of #263

**Closed by SleepyPxnda** 2024-07-20 19:59 UTC
Labels: bug, needs validation
