### ISSUE TITLE
[Bug]: Bandana Preview Bug

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#370] opened 2024-08-29 20:00 UTC
### How to reproduce ?

In der Cosmetic Preview glitcht das Bandana unter den Kopf. (Ich habe keinen 2nd Layer)
![image](https://github.com/user-attachments/assets/371bae96-22bc-43cc-8736-6b2e830b4550)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment] 2024-08-31 10:35
Duplicate of #235

**Closed by SleepyPxnda** 2024-08-31 10:35 UTC
Labels: bug, needs validation
