### ISSUE TITLE
[FEATURE-REQUEST]: Capes in Launcher deleten

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#669] opened 2024-12-08 09:08 UTC
### Your idea

@TimLohrer 

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by BigBrainRobin29** [comment] 2024-12-08 10:18
Duplicate of #603

**Closed** 2024-12-08 12:36 UTC
Labels: feature request, launcher related
